# Generated by Django 4.0.2 on 2022-03-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default='98-85', max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='255.255.255.255', max_length=15)),
                ('login', models.CharField(default='login', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('tags', models.ManyToManyField(to='password_manager_app.Tag')),
            ],
        ),
    ]
