# Generated by Django 4.0.2 on 2022-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='85-49', max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
