# Generated by Django 4.0.2 on 2022-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='ip',
            field=models.CharField(default='250.192.63.255', max_length=15),
        ),
    ]
