# Generated by Django 4.0.2 on 2022-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0006_alter_passwordmanager_ip_alter_passwordmanager_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='ip',
            field=models.CharField(default='168.149.10.62', max_length=15),
        ),
        migrations.AlterField(
            model_name='passwordmanager',
            name='tags',
            field=models.ManyToManyField(blank=True, to='password_manager_app.Tag'),
        ),
    ]
